# Numpy

## How to import Numpy

In [1]:
import numpy as np

## Array

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])

[1 2 3 4]


### Creating Array

Cara membuat array : 

- np.array()

- np.zeros()

- np.ones()

- np.empty()

- np.arange()

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
np.arange(0,10,2)    #(start,stop,step)

array([0, 2, 4, 6, 8])

### Add, Remove, and Sort

- Menambahkan elemen array : np.append()
- Menghapus elemen array : np.delete()
- Mangurutkan elemen array : np.sort()

In [8]:
ar = np.array([8,4,2,6])

In [9]:
np.append(ar, [1,2])

array([8, 4, 2, 6, 1, 2])

In [10]:
np.delete(ar, 1)

array([8, 2, 6])

In [11]:
np.sort(ar)

array([2, 4, 6, 8])

### Shape and Size

- Mengetahui jumlah axes/dimensi array : ndarray.ndim()     
- Mengetahui jumlah total elemen array : ndarray.size()      
- Mengetahui jumlah elemen yg disimpan di setiap dimensi array : ndarray.shape()     

In [12]:
array_example = np.array ([
    [[0,1,2,3],
    [4,5,6,7]],
    
    [[8,9,10,11],
    [12,13,14,15]]
])
print (array_example)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [13]:
array_example.ndim

3

In [14]:
array_example.size

16

In [15]:
array_example.shape    #(2,2,4) larik 2D dengan 2 baris dan 4 kolom

(2, 2, 4)

### Reshape

- Memberikan bentuk baru ke array tanpa mengubah datanya : np.reshape()

In [16]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [17]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [18]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

Untuk meningkatkan dimensi array yg sudah ada :
- np.newaxis
- np.expand_dims

In [19]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [20]:
#use np.newaxis to add a new axis
a2 = a [np.newaxis]
print(a2)
print(a2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [21]:
#you can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [22]:
#for a column vector, you can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
#you can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [24]:
#you can add an axis at index position 0 with:

c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

In [25]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [26]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [28]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [29]:
#you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [30]:
#you can select elements that satisfy two conditions using the & and | operators

c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

Mengindeks dan slicing array : 
- np.vstack()
- np.hstack()
- np.hsplit()
- .view()
- .copy()

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [33]:
a_1=np.array([[1,1],
             [2,2]])
a_2=np.array([[3,3],
             [4,4]])

In [34]:
np.vstack((a_1, a_2))     #menumpuk vertikal

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
np.hstack((a_1, a_2))     #menumpuk horizontal

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [36]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                    [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [37]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
c = a.copy()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Basic Array Operations

In [41]:
a = np.array([1,2,3,4])
a.sum()

10

In [42]:
b=np.array([[1,1], [2,2]])
print(b)
b.sum(axis=0)    #sum the columns

[[1 1]
 [2 2]]


array([3, 3])

In [43]:
b.sum(axis=1)    #sum the rows

array([2, 4])

In [44]:
data = np.array([1,2])
data

array([1, 2])

In [45]:
ones = np.ones(2)
ones

array([1., 1.])

In [46]:
print(data+ones)
print(data*data)
print(data/data)

[2. 3.]
[1 4]
[1. 1.]


### Broadcasting

In [47]:
data*2

array([2, 4])

### More Array Operations

In [48]:
data.max()
data.min()
data.sum()

3

In [49]:
A = np.array([[4.9, 3, 6.3, 4.5],
             [3.2, 2.6, 8.9, 4.3]])
print(A)

[[4.9 3.  6.3 4.5]
 [3.2 2.6 8.9 4.3]]


In [50]:
A.sum()

37.7

In [51]:
A.min()

2.6

In [52]:
A.min(axis=0)

array([3.2, 2.6, 6.3, 4.3])

In [53]:
A.max()

8.9

In [54]:
A.max(axis=1)

array([6.3, 8.9])

In [55]:
A.std

<function ndarray.std>

## Matrices

### Creating Matrices

In [56]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [57]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.09901659, 0.88680917],
       [0.24070082, 0.2235646 ],
       [0.83241866, 0.21355192]])

In [58]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.81933834 0.62262382]
 [0.03683067 0.52266854]
 [0.11584052 0.3817167 ]]


### Matrix Arithmatic

In [59]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [60]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [61]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [62]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [63]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [64]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2=np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [65]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [66]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[0:1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[[1 2]]
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [67]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [68]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [69]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

#### Transpose

In [70]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [71]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [72]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### Reshape

In [73]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [76]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [77]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [78]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [79]:
print(np.random.random((4,3,2)))

[[[0.34693881 0.00651587]
  [0.29516948 0.39917524]
  [0.49749795 0.58050957]]

 [[0.55114615 0.10203453]
  [0.44800032 0.04814095]
  [0.88320264 0.48870139]]

 [[0.13156906 0.55625339]
  [0.56147422 0.48534627]
  [0.96309161 0.61327226]]

 [[0.7985392  0.44557112]
  [0.44068385 0.17859422]
  [0.29666144 0.06855899]]]


### Flatten N-Dimensional Array

In [80]:
arrflat = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

Rumus mean square error : 

error = (1/n) * np.sum(np.square(observed-prediction))